# Numpy
NumPy（Numerical Python的简称），是科学计算基础的一个库，提供了大量关于科学计算的相关功能，例如，线性变换，数据统计，随机数生成等。其提供的最核心的类型为多维数组类型（ndarray）。

## 使用方式
可以使用如下的方式来安装numpy库：  
`pip install numpy`  
根据惯例，使用numpy库的导入方式为：  
`import numpy as np`  
在导入之后，我们可以通过：  
`np.__version__`  
来查看Numpyu库的版本信息。

In [33]:
import numpy as np
# In与Out都是IPython的特殊对象。用来存储我们输入与输出的值。
# In是列表类型，Out是字典类型。
# print(np.__version__)

# 如果不使用print输出，而是作为表达式计算值显示时，我们只能看到最后一个结果。
print(np.__version__)
print(5 + 3)

1.11.1
8


## 数组的创建
Numpy提供了很多方式（函数）来创建数组对象，常用的方式如下：
* array
* arange
* ones / ones_like
* zeros / zeros_like
* empty / empty_like
* full / full_like
* eye / identity
* linspace
* logspace

说明：
* 注意arange函数，不是arrange。
* arange与linspace的区别。

In [21]:
from IPython.display import display
# numpy最核心的类型，就是多维数组类型numpy.ndarray。
# 传递一个列表（list），创建数组
n = np.array([1, 2, 3])
print(n)

# 在输出显示时，优先使用display，这样可以比print显示更加友好。【与Out对象中显示的格式是一样的。】
display(5 + 3)
display(n)

# 创建多维数组
n = np.array([[1, 2], [3, 4], [5, 6]])
display(n)

[1 2 3]


8

array([1, 2, 3])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
# 类似与python中的range函数。
n = np.arange(10)
display(n)
n = np.arange(5, 15)
display(n)

# 指定步长
n = np.arange(5, 15, 2)
display(n)

# 不同于range，arange的步长还支持浮点类型。
n = np.arange(1, 2, 0.1)
display(n)

# 步长也可以为负值。
n = np.arange(2, 1, -0.1)
display(n)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

array([ 5,  7,  9, 11, 13])

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

array([2. , 1.9, 1.8, 1.7, 1.6, 1.5, 1.4, 1.3, 1.2, 1.1])

In [17]:
# 创建值全为1的数组。
n = np.ones((3, 4))
display(n)
n = np.array([[1, 2], [3, 4]])
display(n)

# 创建一个与参数数组形状相同的数组，值全为1。
x = np.ones_like(n)
display(x)

# 创建全为0的数组。
x = np.zeros((2, 5))
x = np.arange(20).reshape(4,5)
y1 = np.ones_like(x)
y2 = np.zeros_like(x)
display(x, y1, y2)

# 创建值全为空的数组。（值并非是为空，而是值尚未经过初始化）
x = np.empty(3)
x = np.arange(20).reshape(4,5)
y = np.empty_like(x)
display(x, y)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

array([[1, 2],
       [3, 4]])

array([[1, 1],
       [1, 1]])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [28]:
# 创建指定值的数组
x = np.full((3, 4), 2.)
y = np.full_like(x, 33)
display(x, y)
display(np.ones((3, 4)))

# 创建单位矩阵
display(np.eye(5))
display(np.identity(5))

# 创建等差数列的数组。
# num指定数组元素的个数。endpoint指定是否包含终止点。（默认为True，包含）
display(np.linspace(1, 50, num=50, endpoint=True))

# 创建等比数列的数组。（前面两个参数指定指数）
# num指定数组元素的个数。endpoint指定是否包含终止点。
# base用来指定底数，默认为10。
display(np.logspace(1, 10, num=20, endpoint=False, base=2))

# 说明：
# 注意：arange与linspace。
# 二者都可以产生一系列区间值。
# 对于arange，更关注的是数值之间的间隔（步长）是多少，而不太关注具体会产生多少数值。
# 对于linspace，更关注的是数值的个数，而不太关注数值之间的距离是多少。

array([[ 2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.]])

array([[ 33.,  33.,  33.,  33.],
       [ 33.,  33.,  33.,  33.],
       [ 33.,  33.,  33.,  33.]])

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.])

array([   2.        ,    2.73208051,    3.73213197,    5.09824251,
          6.96440451,    9.51365692,   12.99603834,   17.75311155,
         24.25146506,   33.12847756,   45.254834  ,   61.81992505,
         84.44850629,  115.36005921,  157.58648491,  215.2694823 ,
        294.06677888,  401.70705812,  548.74801282,  749.61187632])

## 数组（ndarray）与列表（List）
数组与列表类似，是具有相同类型的多个元素构成的整体。  
局限：
* 数组元素要求是相同类型，而列表的元素可以是不同类型。

优势：
* 数组可以与标量进行运算，数组之间也可以进行矢量化运算。【对应位置的元素进行运算，无需进行循环操作。这样就可以充分利用现代处理器SIMD Single Instruction,Multiple Data的方式进行并行计算】。
* 数组在运算时，具有广播能力。【可根据需要进行元素的扩展，完成运算。】
* 数组底层使用C程序编写，运算速度快。
* 数组底层使用C中数组的存储方式（紧凑存储），节省内存空间。

## 应用对比
* 将两个等长的列表（数组）分别进行数学运算（例如，+, -等）。
* 将一个列表（数组）中的所有元素进行相同的改变。
* 对步骤2进行计时，衡量时间消耗。（练习）
* 创建相同大小的列表（数组），衡量内存消耗。（练习）

In [31]:
# 班级中每个学生的年龄
# 如果是列表，则需要进行循环的操作。
li = [15, 16, 14]
for i in range(len(li)):
    li[i] += 1
display(li)

# 如果是ndarray数组，则无需循环，直接进行矢量化运算。
a = np.array([15, 16, 14])
a = a + 1
# 数组可以与标量执行运行。【实际上会扩散到数组中每个元素与该标量执行运算。】
a += 1
display(a)

# 数组之间也可以进行矢量化运算。
# 此时，就是数组中对应元素执行相应的运算。
b = np.array([10, 20, 30])
display(a + b)

# ndarray数组具有广播的能力。
# 数组与标量运算，实现的广播。
a += 1
display(a)

# 数组与数组之间，实现的广播。
c = np.array([[1, 2, 3], [1, 2, 3]])
display(b + c)

[16, 17, 15]

array([17, 18, 16])

array([27, 38, 46])

array([18, 19, 17])

array([[11, 22, 33],
       [11, 22, 33]])

In [47]:
# 对列表执行运算，需要使用循环
li1 = [1, 2, 3]
li2 = [4, 5, 6]
li3 = []
for x, y in zip(li1, li2):
    li3.append(x + y)
print(li3)

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b
display(c)

[5, 7, 9]


array([5, 7, 9])

In [48]:
%%timeit li = list(range(100000))
for i in range(len(li)):
    li[i] += 1

5.54 ms ± 9.43 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [49]:
%%timeit a = np.arange(100000)
a += 1

29.3 µs ± 31.2 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
%load_ext memory_profiler

In [ ]:
%%writefile test.py
import numpy as np

def m():
    li = list(range(100000))
    a = np.arange(100000)
    del li
    del a

In [34]:
import test

In [ ]:
%mprun -f test.m test.m()

## <font color="green">为什么数组会比列表快，而且快很多？</font>

## 相关属性与操作
数组对象具有如下常用属性：
* ndim
* shape
* dtype
* size
* itemsize

In [50]:
x = np.array([[1, 2, 3], [3, 4, 5]])
# 获取数组的维度
display(x.ndim)
# 获取数组的形状（每个维度上的长度）。返回一个元组。
display(x.shape)
# 获取数组的元素类型。
display(x.dtype)
# 返回数组元素的个数。(整体所有元素的个数)
display(x.size)
# 返回数组元素占用空间的大小。以字节为单位。
display(x.itemsize)

2

(2, 3)

dtype('int32')

6

4

## 数据类型
* 在创建数组时，也可以使用dtype来显式指定数组中元素的类型（通过numpy提供的类型进行指定）。
* 如果没有指定，则会根据元素类型进行推断。
* 如果元素的类型不同，则会选择一种兼容的类型。

In [52]:
# 如果创建时没有指定元素的类型，则会根据现有元素，自动推断元素类型。
# u32表示32位无符号char值
x = np.array([1, 2, 3., "abc"])
display(x.dtype)

# 注意：不同的数据顺序，可能会影响到最终的数组类型。
y = np.array(["abc", 1, 2, 3.])
display(y.dtype)

# 在数据存储上，有两种形式：
# 1 高位优先 >
# 2 低维优先 <
# 我们在创建数组时，可以使用dtype参数显式指定数组的类型。
w = np.array([1, 2, 3], dtype=np.float32)
display(w.dtype)

dtype('<U32')

dtype('<U3')

dtype('float32')

## 类型转换
我们可以通过数组对象的astype函数来进行类型转换。
## <font color="green">是否可以直接修改dtype属性进行类型转换？</font>

In [53]:
x = np.array([1.5, 2.3, 3.4, -1.2, -1.8, -1.5])
display(x.dtype)
y = x.astype(np.int64)
display(y)

# 直接修改dtype属性，尝试修改数组类型。
x.dtype = np.int
display(x)

dtype('float64')

array([ 1,  2,  3, -1, -1, -1], dtype=int64)

array([          0,  1073217536,  1717986918,  1073899110,   858993459,
        1074475827,   858993459, -1074580685,  -858993459, -1073951540,
                 0, -1074266112])

## 改变形状
我们可以通过数组对象的reshape方法（或者np的reshape函数）来改变数组的形状。  

说明：
* 改变数组形状时，如果维度大于1，可以将某一个维度设置为-1。
* numpy中存在很多方法，既可以使用np来访问，也可以通过数组对象来访问。

In [64]:
x = np.arange(10)
display(x)

# numpy中，提供了很多功能函数，既可以通过np的方式调用，也可以通过ndarray数组对象来进行调用。
y = np.reshape(x, (5, 2))
display(y)

# 通过数组对象调用reshape，shape形状参数，我们既可以传一个元组，也可以分开传入。
# 通过np方式调用reshape，只能通过元组形式传入。
y = x.reshape(2, 5)
display(x.shape, y.shape)

# 不建议这样做
x.shape = (2, 5)
display(x)

# 级联操作
np.arange(30).reshape(5, 6)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

(10,)

(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

## 索引与切片
在Python中，序列类型支持索引与切片操作，在numpy库中，ndarray数组也支持类似的操作。不过，二者之间既有相同点，也有不同点。
### 相似点
数组对象也支持索引与切片操作，语法与Python中序列类型的索引与切片相似。  
当数组是多维数组时，可以使用array\[高维, 低维\]的方式按维度进行索引或切片。  
### 不同点
数组的切片返回的是原数组数据的视图（回忆：Python中呢？）。如果需要复制底层的数组元素，可以使用数组对象的copy方法。  
注意：视图是共享底层的数组元素，但视图并不是赋值。

思考：通过切片，我们可以选取多个元素，但是，如果我们要选取的低维数组（或元素）是不连续的，该怎样做？


In [80]:
x = np.arange(30).reshape(5, 6)
display(x)
display(x[1][2])

# 也可以这样获取元素
display(x[1, 2])

# 切片,是第一个维度的数据，都倒过来
y = x[::-1, ::-1]
display(y)

li = [1, 2, 3, 4, 5]
# python中，切片是浅拷贝。
li2 = li[:]
li[0] = 100
display(li, li2)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

8

8

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

[100, 2, 3, 4, 5]

[1, 2, 3, 4, 5]

In [86]:
y = x[0:3, 0:3]
display(y)
# x[0][0] = 1000
y[0][0] = 2000
display(x, y)

array([[2000,    1,    2],
       [   6,    7,    8],
       [  12,   13,   14]])

array([[2000,    1,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10,   11],
       [  12,   13,   14,   15,   16,   17],
       [  18,   19,   20,   21,   22,   23],
       [  24,   25,   26,   27,   28,   29]])

array([[2000,    1,    2],
       [   6,    7,    8],
       [  12,   13,   14]])

In [90]:
# 注意，ndarray数组切片，返回的是原数据的视图。
# 但是，这种视图是共享底层的数据，并不是一种赋值。

y = x[:]
print(x is y)

# 可以通过数组对象的copy方法，实现底层数据的复制，而不是返回底层数据的视图。
y = x.copy()
x[0][0] = 2000
display(x, y)

False


array([[2000,    1,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10,   11],
       [  12,   13,   14,   15,   16,   17],
       [  18,   19,   20,   21,   22,   23],
       [  24,   25,   26,   27,   28,   29]])

array([[1000,    1,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10,   11],
       [  12,   13,   14,   15,   16,   17],
       [  18,   19,   20,   21,   22,   23],
       [  24,   25,   26,   27,   28,   29]])

## 通过整数数组进行索引
当要选取的元素不连续时，可以提供一个索引数组来选择（或修改）对应索引位置的元素。

说明：
* 通过整数数组索引，返回的是原数组的拷贝，而不是视图。
* 可以提供多个一维数组索引，此时会将每个数组的对应位置元素作为索引，返回对应的元素。

In [36]:
x = np.arange(30).reshape(5, 6)
# display(x)
# index = [1, 3, 4]
# display(x[index])
# display(x[0:2])
# display(x[[0, 1]])

# 通过整数数组，进行索引（提取元素），返回的是原数组数据的拷贝，而不是视图。（这点与切片不同）
y = x[[1, 3]]
display(y)
y[0, 0] = 2000
display(x, y)

# 提供多个一维数组，提取（获取）元素。
# 每个一维数组指定相应维度的索引（坐标）。
x[[0, 2, 3], [1, 3, 4]]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

array([[2000,    7,    8,    9,   10,   11],
       [  18,   19,   20,   21,   22,   23]])

array([ 1, 15, 22])

## 通过布尔数组进行索引
我们可以提供一个布尔类型的数组（A），然后通过该数组（A）来对另外一个数组（B）进行索引（元素选取）。索引的原则为：如果为True，则选取对应位置的元素，否则不选取。<br>
通过布尔类型的数组进行索引是常见且实用的操作，我们通常用来进行元素选择（或过滤）操作。例如：
* 选择一个公司中所有年龄大于15的年龄。
* 选择两个数组中对应位置相同的元素。
* 将所有大于100的值设置为100。

说明：
* 用于索引的布尔数组通常通过现有数组计算得出。
* 可以通过~对条件进行取反操作（不能使用not）。
* 当存在多个条件时，可以使用&，|符号（不能使用and与or）,同时，每个条件需要使用()进行括起。

In [109]:
x = np.arange(10,30).reshape(4, 5)
display(x)
# 我们可以通过布尔类型数组（列表）来选择元素。依据：如果是True，则提取（保留），如果是False，则去掉。
display(x[[True, False, True, False]])
display(x > 15)

a = np.array([1, 3, 9, 10])
b = np.array([1, 8, 6, 10])
display(a[[True, False, False, True]])
display(a[a == b])
a = np.array([102, -3, 234, 120, -123, 50])
display(a[a > 100])


# 在numpy中，实现Python中的and，or，与not
# and ->  &
# or  ->  |
# not -> ~
# 注意：在进行条件组合的时候，每个条件使用小括号括起。【别再看运算符优先级了，此处不适用。】
a[(a > 100) & (a < 150)] = 100
display(a)
b = a[~(a > 100)]
display(b)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

array([ 1, 10])

array([ 1, 10])

array([102, 234, 120])

array([ 100,   -3,  234,  100, -123,   50])

array([ 100,   -3,  100, -123,   50])

## 数组扁平化
我们可以通过调用ravel或flatten方法，对数组对象进行扁平化处理。
* np.ravel / ravel
* flatten

二者的区别在于，ravel返回原数组的视图，而flatten返回原数组的拷贝。

In [112]:
x = np.arange(12).reshape(3, 2, 2)
display(x)
display(x.ravel())
display(np.ravel(x))
display(x.flatten())

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [114]:
# 二者的区别在于，ravel返回原数组的视图，而flatten返回原数组的拷贝。
y = x.ravel()
y[0] = 1000
display(x, y)

y = x.flatten()
y[0] = 2000
display(x, y)

array([[[1000,    1],
        [   2,    3]],

       [[   4,    5],
        [   6,    7]],

       [[   8,    9],
        [  10,   11]]])

array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11])

array([[[1000,    1],
        [   2,    3]],

       [[   4,    5],
        [   6,    7]],

       [[   8,    9],
        [  10,   11]]])

array([2000,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11])

## 数组的存储顺序

在创建数组时，我们可以通过order参数来指定数组元素的存储顺序。存储顺序分为四种：
* C 行优先
* F 列优先
* K
* A

In [116]:
x = np.array(range(1,13)).reshape((3, 4), order="C")
y = np.array(range(1,13)).reshape((3, 4), order="F")
display(x)
display(y)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

## <font color="green">练习</font>
<font color="green">1 直接使用array去创建一个多维数组（如2 \* 2），order分别设置为C与F，二者会有不同吗？  
2 创建一个2 \* 3（3 \* 2）的数组，将其reshape为3 \* 2（2 \* 3），order分别设置为C与F，解释结果。</font>

In [118]:
x = np.array([[1, 2], [3, 4], [5, 6]], order="C")
y = np.array([[1, 2], [3, 4], [5, 6]], order="F")

# order 影响两方面，一是数据抽取（扁平化处理）的顺序。二是数据构建（数组填充）的顺序。
display(x, y)

array([[1, 2],
       [3, 4],
       [5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [120]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x = x.reshape(3, 2, order="C")
y = np.array([[1, 2, 3], [4, 5, 6]])
display(y)
y = y.reshape(3, 2, order="F")
display(x, y)

x = np.array([[1, 2], [3, 4], [5, 6]])
x = x.reshape(2, 3, order="C")
y = np.array([[1, 2], [3, 4], [5, 6]])
y = y.reshape(2, 3, order="F")
display(x, y)

array([[1, 2, 3],
       [4, 5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

array([[1, 5],
       [4, 3],
       [2, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

array([[1, 5, 4],
       [3, 2, 6]])

我们在创建数组时，在读取（解析）现有的数据顺序，以及创建新的数据的结构上，都会使用order指定的顺序。

可以简单认为，我们先使用指定的order将原数据扁平化处理，然后在使用指定的order顺序去构建新的数组（向新的数组中插入值）。

## 通用函数ufunc（universal function）
Numpy提供了许多通用函数，这些通用函数可以看做是以前通过Python计算的矢量化版本。

* abs / fabs
* ceil / floor
* exp
* log / log2 / log10
* modf
* sin / sinh / cos / cosh
* sqrt

In [124]:
x = np.array([1, 2, 3, 4, -1, -2, -3, -4])
y = np.abs(x)
display(y)

y = np.array([1.3, 2.5, -10, 3, 5.5])
# 返回一个元组，含有两个元素（数组类型），第一个元素返回小数部分，第二个元素返回整数部分。
np.modf(y)

array([1, 2, 3, 4, 1, 2, 3, 4])

(array([ 0.3,  0.5, -0. ,  0. ,  0.5]), array([  1.,   2., -10.,   3.,   5.]))

## 统计函数
Numpy（或数组对象）具有如下常用的统计函数。  
* mean / sum
* max / min
* argmax / argmin
* std / var
* cumsum / cumprod

### 轴（axis）
可以指定axis参数来改变统计的轴。axis是一个非常重要的参数，关于数组的很多操作与运算，都涉及该参数。轴的取值为0,1,2……其中0表示最高的维度，1表示次高的维度，以此类推。同时，轴也可以为负值，表示倒数第n个维度，例如，-1表示最后（低）一个维度。在二维数组中，0表示沿着竖直方向进行操作，1表示沿着水平方向进行操作。在多维数组中，轴相对复杂一些，可以认为，是沿着轴所指定的下标变化的方向，进行操作。例如，如果轴是1，则根据第1个下标变化的方向上进行操作。

In [134]:
x = np.arange(1,11).reshape(2, 5)
display(x)

# 平均值，
display(np.mean(x), np.sum(x))
display(np.max(x), np.min(x))

# 返回最大值（最小值）的索引。
display(np.argmax(x), np.argmin(x))

# 标准差， 方差
display(np.std(x), np.var(x))

# 求累积和与累积乘积
display(np.cumsum(x), np.cumprod(x))
# 如果没有指定额外参数，统计函数就相当于对整个数组所有元素进行统计。（将数组扁平化处理，然后对所有元素进行操作。）

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

5.5

55

10

1

9

0

2.8722813232690143

8.25

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55], dtype=int32)

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800], dtype=int32)

In [140]:
# 在统计的时候，我们可以指定轴的方向，来进行统计。
x = np.arange(10, 0, -1).reshape(2, 5)
display(x)

# 按竖直方向统计
display(np.sum(x, axis=0))

# 按水平方向统计
display(np.sum(x, axis=1))
display(np.sum(x, axis=-1))

# reshape形状是多维时，可以将其中一个维度指定为-1，表示根据其他维度的大小，来自动计算该维度的大小。【至多只能有一个-1。】
x = np.arange(30).reshape(6, -1)
display(x)

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

array([15, 13, 11,  9,  7])

array([40, 15])

array([40, 15])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [143]:
import numpy as np
x = np.arange(24).reshape(2, 3, 4)
display(x)
display(x.sum(axis=0))
display(x.sum(axis=1))
display(x.sum(axis=2))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

array([[ 6, 22, 38],
       [54, 70, 86]])

## 随机函数
* np.random.rand
* np.random.random 与rand相同，但是形状通过一个参数指定。
* np.random.randn
* np.random.normal
* np.random.randint
* np.random.seed
* np.random.shuffle
* np.random.uniform

## 连接与拆分函数
* np.concatenate 对多个数组按指定轴的方向进行连接。
* np.vstack / np.hstack
* np.split / np.hsplit / np.vsplit

In [158]:
x = np.random.uniform()
display(x)

0.17421631534553328

## 其他函数（方法）
* any / all
* transpose（T）
* dot（@）
* sort / np.sort
* unique
* np.where
* np.save / np.load
* np.savetxt / np.loadtxt

说明：
* sort可以指定排序的轴。
* save在保存数组时，如果没有指定扩展名，则自定补充.npy作为扩展名。
## <font color="green">数据对象与numpy都具有sort方法（函数），二者等价吗？</font>